# Generated by Django 2.1 on 2020-06-06 14:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blog',
            old_name='blog',
            new_name='blog_type',
        ),
    ]
